### ISSUE TITLE
linux 环境下无法使用此插件

### ISSUE THREAD

**Issue by dingyi222666** [QuanhuZeYu/koishi-plugin-qhzy-sharp#1]
在 linux（docker）使用此插件出现如下错误

```text
app Error: Could not load the "sharp" module using the linuxmusl-x64 runtime
                        ERR_DLOPEN_FAILED: Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /koishi/data/assets/qhzy/sharp/package/sharp-linuxmusl-x64.node)
                        Possible solutions:
                        - Ensure optional dependencies can be installed:
                            npm install --include=optional sharp
                        - Ensure your package manager supports multi-platform installation:
                            See https://sharp.pixelplumbing.com/install#cross-platform
                        - Add platform-specific dependencies:
                            npm install --os=linux --libc=musl --cpu=x64 sharp
- Consult the installation documentation:
                            See https://sharp.pixelplumbing.com/install
                            at Object.<anonymous> (/koishi/node_modules/@quanhuzeyu/sharp-for-koishi/lib/sharp.js:161:9)
                            at Module._compile (node:internal/modules/cjs/loader:1358:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
                            at Module.load (node:internal/modules/cjs/loader:1208:32)
                            at Module._load (node:internal/modules/cjs/loader:1024:12)
                            at Module.require (node:internal/modules/cjs/loader:1233:19)
                            at require (node:internal/modules/helpers:179:18)
                            at Object.<anonymous> (/koishi/node_modules/@quanhuzeyu/sharp-for-koishi/lib/constructor.js:10:1)
                            at Module._compile (node:internal/modules/cjs/loader:1358:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1416:10
```

发现 `data/assets/qhzy/sharp` 底下并没有 `libvips` 相关二进制文件，可能需要另外下载或者构建此二进制文件。

**Comment by dingyi222666** [comment]
还有，此插件依赖 `tar`，请将 tar 放入 dependencies，否则在全新 koishi 环境安装此插件可能会出现如下错误

![f0064b3482fa4f21810a3e9e4d29e6b0](https://github.com/user-attachments/assets/f3e1ef01-ee3c-447c-9020-4a047b68cabe)

**Comment by QuanhuZeYu** [comment]
我是硬编码写的，等会去加

**Comment by QuanhuZeYu** [comment]
> 还有，此插件依赖 `tar`，请将 tar 放入 dependencies，否则在全新 koishi 环境安装此插件可能会出现如下错误
> 
> ![f0064b3482fa4f21810a3e9e4d29e6b0](https://private-user-images.githubusercontent.com/48376989/366012796-f3e1ef01-ee3c-447c-9020-4a047b68cabe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjc4NTUsIm5iZiI6MTcyNjEyNzU1NSwicGF0aCI6Ii80ODM3Njk4OS8zNjYwMTI3OTYtZjNlMWVmMDEtZWUzYy00NDdjLTkwMjAtNGEwNDdiNjhjYWJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3NTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNTg2N2U5YjE5OWUxNDFiN2YyMmJiMjA1YjhmZTU3ODNmMzFjZTVlYmQ0YThlYmQ5YzE5ZjJmMWM0ZTVjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tBuHothoRs0d8OSynqoqjtAvDAQsBxII-juf9lKoaWg)

最新版本已经改为使用npm install来动态编译，我没有linux环境测试不知道可以可以解决你的问题，你可以先试试

**Comment by QuanhuZeYu** [comment]
linux环境我不太会弄，你也可以自己编译好之后塞到 `... sharp/@img/linux-...` 文件夹

**Comment by QuanhuZeYu** [comment]
新版使用node服务插件代理来安装，linux问题已解决
